language: node_js

node_js: stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --frozen-lockfile

script: yarn test

after_success: yarn coverage && nyc report --reporter=text-lcov | coveralls
